package com.stardusted1.Sendicate.app.rest.users;

import com.stardusted1.Sendicate.app.core.repositories.ReceiverRepository;
import com.stardusted1.Sendicate.app.core.users.Receiver;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.json.BasicJsonParser;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

@RestController    // This means that this class is a Controller
@RequestMapping(path = "api/users/receivers")
public class ReceiverController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private ReceiverRepository receiverRepository;

	@PostMapping("{id}")
	Map<String,Object> updateUser(@PathVariable("id") String id,
					  @RequestBody String body) {
		var user = receiverRepository.findById(id);
		Map<String, Object> request = new BasicJsonParser().parseMap(body);
		if (user.isEmpty()) {
			return null;
		} else {
			boolean isChanged = false;
			Receiver receiver = user.get();
			Receiver receiver1 = (Receiver) ((Optional)SecurityContextHolder.getContext().getAuthentication().getPrincipal()).get();
			if (request.get("emailaddr") != null) {
				receiver.addEmail((String) request.get("emailaddr"));
				receiver1.addEmail((String) request.get("emailaddr"));

				isChanged = true;
			}
			if (request.get("phone") != null) {
				receiver.addPhone((String) request.get("phone"));
				receiver1.addPhone((String) request.get("phone"));
				isChanged = true;
			}
			if (request.get("name") != null) {
				isChanged = true;
				receiver.setName((String) request.get("name"));
				receiver1.setName((String) request.get("name"));
			}
			if (isChanged)
				receiverRepository.save(receiver);
		}

		return request;
	}

	@PostMapping(path = "{id}/delete/{token}")
	String deleteReceiver(@PathVariable("id") String id,
						  @PathVariable("token") String token) {
		var user = receiverRepository.findById(id);
		if (user.isEmpty()) {
			return "no";
		} else {
			Receiver receiver = user.get();
			if (receiver.getToken().equals(token)) {
				//receiverRepository.delete(receiver);
				return "deleted";
			}
		}
		return "ok";
	}

	@PostMapping(path = "/add")
		// Map ONLY POST Requests
	String addNewReceiver(@RequestParam String name
			, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		return "Saved";
	}


	@GetMapping(path = "/all")
	public @ResponseBody
	Iterable<Receiver> getAllReceiver() {
		// This returns a JSON or XML with the users
		return receiverRepository.findAll();
	}
}
