package com.stardusted1.Sendicate.app.rest.users;

import com.stardusted1.Sendicate.app.core.users.Receiver;
import com.stardusted1.Sendicate.app.core.repositories.ReceiverRepository;
import com.stardusted1.Sendicate.app.service.System;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

@Controller    // This means that this class is a Controller
@RequestMapping(path="api/users/receivers")
public class ReceiverController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ReceiverRepository receiverRepository;

    @PostMapping("{id}")
    String updateUser(@PathVariable("id") String id,
                      @RequestBody String body){
        var user = receiverRepository.findById(id);
        if(user.isEmpty()){
            return "no";
        }else {
            Receiver receiver = user.get();
            Map<String,String> request = System.parseBody(body);
            receiver.addEmail(request.get("emailaddr"));
            receiver.addPhone(request.get("phone"));
            receiver.setName(request.get("username"));
            receiverRepository.save(receiver);
        }
        return "ok";
    }
	@PostMapping(path = "{id}/delete/{token}")
	String deleteReceiver(@PathVariable("id") String id,
					  @PathVariable("token") String token){
		var user = receiverRepository.findById(id);
		if(user.isEmpty()){
			return "no";
		}else {
			Receiver receiver = user.get();
			if(receiver.getToken().equals(token)){
				//receiverRepository.delete(receiver);
				return "deleted";
			}
		}
		return "ok";
	}

    @PostMapping(path="/add") // Map ONLY POST Requests
    String addNewReceiver (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        return "Saved";
    }



    @GetMapping(path="/all")
    public @ResponseBody
    Iterable<Receiver> getAllReceiver () {
        // This returns a JSON or XML with the users
        return receiverRepository.findAll();
    }
}
