package com.stardusted1.Sendicate.app.rest;

import com.stardusted1.Sendicate.app.core.repositories.DeliverymanRepository;
import com.stardusted1.Sendicate.app.core.repositories.ProviderRepository;
import com.stardusted1.Sendicate.app.core.repositories.ReceiverRepository;
import com.stardusted1.Sendicate.app.core.users.Deliveryman;
import com.stardusted1.Sendicate.app.core.users.Provider;
import com.stardusted1.Sendicate.app.core.users.Receiver;
import com.stardusted1.Sendicate.app.core.users.User;
import com.stardusted1.Sendicate.app.service.System;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.Date;

@RestController
@RequestMapping("api/login")
public class AuthenticationController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private ReceiverRepository receiverRepository;
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private DeliverymanRepository deliverymanRepository;
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private ProviderRepository providerRepository;

	private System system= new System();

	@PostMapping(path="/forgot_password")
	String forgot_password(
			@RequestParam String name) {
		try{
			system.renewPassword(name);
			return "Ok";
		}catch (Exception e){
			return "Something went wrong";
		}
	}

	@PostMapping()
	String login(@RequestParam String login,
				 @RequestParam String pass) {
		try{
			return system.AuthenticateUser(login,pass);
		}catch (Exception e){
			return "Something went wrong";
		}
	}

	@PostMapping("register")
	User register(@RequestParam String name,
				  @RequestParam String pass,
				  @RequestParam String email,
				  @RequestParam String type,
				  @RequestParam String phone) {
		if(Integer.valueOf(type)==1){
			Provider provider = new Provider();
			provider.setPassword(pass);
			provider.setName(name);
			provider.getEmails().add(email);
			provider.getPhones().add(phone);
			provider.setDateOfRegistration(new Date());
			providerRepository.save(provider);
			return provider;
		}
		if(Integer.valueOf(type)==2){
			Deliveryman deliveryman = new Deliveryman();
			deliveryman.setPassword(pass);
			deliveryman.setName(name);
			deliveryman.getEmails().add(email);
			deliveryman.getPhones().add(phone);
			deliveryman.setDateOfRegistration(new Date());
			deliverymanRepository.save(deliveryman);
			return deliveryman;
		}if(Integer.valueOf(type)==3){
			Receiver receiver = new Receiver();
			receiver.setPassword(pass);
			receiver.setName(name);
			receiver.setEmail(email);
			receiver.setPhone(phone);
			receiver.setDateOfRegistration(new Date());
			receiverRepository.save(receiver);
			return receiver;
		}
		return null;
	}

}
