package com.stardusted1.Sendicate.app.rest;

import com.stardusted1.Sendicate.app.core.users.Receiver;
import com.stardusted1.Sendicate.app.core.repositories.ReceiverRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path="api/receiver")
public class ReceiverController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ReceiverRepository userRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewReceiver (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Receiver n = new Receiver(name,"login","pass");
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody
    Iterable<Receiver> getAllReceiver () {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
